services:

  mermaid-cli:
    image: minlag/mermaid-cli
    working_dir: /work
    volumes:
      - .:/work

  tox:
    image: makukha/multipython:unsafe
    working_dir: /work
    entrypoint: tox
    volumes:
      - mypy_cache:/work/.mypy_cache
      - pip_cache:/root/.cache/pip
      - virtualenv_app_data:/root/.local/share/virtualenv
      - .:/work

volumes:
  mypy_cache:
  pip_cache:
  virtualenv_app_data:
